//Used only for testing should be delted and replaced with actual data from backend
import { UserLocation } from '../constants/location.constant';
import { UserRole } from '../constants/role.constant';
import { User } from '../models/user.model';

export const MOCK_USERS: User[] = [
  {
    firstName: 'Ion',
    lastName: 'Popescu',
    email: 'ion.popescu@example.com',
    role: UserRole.ADMIN,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Maria',
    lastName: 'Ionescu',
    email: 'maria.ionescu@example.com',
    role: UserRole.HR_USER,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Andrei',
    lastName: 'Mureșan',
    email: 'andrei.muresan@example.com',
    role: UserRole.PARTICIPANT,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Elena',
    lastName: 'Dumitrescu',
    email: 'elena.dumitrescu@example.com',
    role: UserRole.MARKETING_ORGANIZER,
    location: UserLocation.TIMISOARA,
    status: true,
  },
  {
    firstName: 'Mihai',
    lastName: 'Stan',
    email: 'mihai.stan@example.com',
    role: UserRole.PARTICIPANT,
    location: UserLocation.TARGU_MURES,
    status: true,
  },
  {
    firstName: 'Ana',
    lastName: 'Radu',
    email: 'ana.radu@example.com',
    role: UserRole.HR_USER,
    location: UserLocation.TIMISOARA,
    status: true,
  },
  {
    firstName: 'George',
    lastName: 'Enescu',
    email: 'george.enescu@example.com',
    role: UserRole.ADMIN,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Cristina',
    lastName: 'Neagu',
    email: 'cristina.neagu@example.com',
    role: UserRole.MARKETING_ORGANIZER,
    location: UserLocation.TARGU_MURES,
    status: true,
  },
  {
    firstName: 'Ion',
    lastName: 'Popescu',
    email: 'ion.popescu@example.com',
    role: UserRole.ADMIN,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Maria',
    lastName: 'Ionescu',
    email: 'maria.ionescu@example.com',
    role: UserRole.HR_USER,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Andrei',
    lastName: 'Mureșan',
    email: 'andrei.muresan@example.com',
    role: UserRole.PARTICIPANT,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Elena',
    lastName: 'Dumitrescu',
    email: 'elena.dumitrescu@example.com',
    role: UserRole.MARKETING_ORGANIZER,
    location: UserLocation.TIMISOARA,
    status: true,
  },
  {
    firstName: 'Mihai',
    lastName: 'Stan',
    email: 'mihai.stan@example.com',
    role: UserRole.PARTICIPANT,
    location: UserLocation.TARGU_MURES,
    status: true,
  },
  {
    firstName: 'Ana',
    lastName: 'Radu',
    email: 'ana.radu@example.com',
    role: UserRole.HR_USER,
    location: UserLocation.TIMISOARA,
    status: true,
  },
  {
    firstName: 'George',
    lastName: 'Enescu',
    email: 'george.enescu@example.com',
    role: UserRole.ADMIN,
    location: UserLocation.CLUJ_NAPOCA,
    status: true,
  },
  {
    firstName: 'Cristina',
    lastName: 'Neagu',
    email: 'cristina.neagu@example.com',
    role: UserRole.MARKETING_ORGANIZER,
    location: UserLocation.TARGU_MURES,
    status: true,
  },
];
