//Used only for testing should be delted and replaced with actual data from backend
import { User } from '../models/user.model';

export const MOCK_USERS: User[] = [
  {
    id: 1,
    firstName: 'Ion',
    lastName: 'Popescu',
    email: 'ion.popescu@example.com',
    role: 'ADMIN',
    location: 'CLUJ-NAPOCA',
    status: 'active',
  },
  {
    id: 2,
    firstName: 'Maria',
    lastName: 'Ionescu',
    email: 'maria.ionescu@example.com',
    role: 'HR_USER',
    location: 'CLUJ-NAPOCA',
    status: 'active',
  },
  {
    id: 3,
    firstName: 'Andrei',
    lastName: 'Mureșan',
    email: 'andrei.muresan@example.com',
    role: 'PARTICIPANT',
    location: 'CLUJ-NAPOCA',
    status: 'active',
  },
  {
    id: 4,
    firstName: 'Elena',
    lastName: 'Dumitrescu',
    email: 'elena.dumitrescu@example.com',
    role: 'MARKETING_ORGANIZER',
    location: 'TIMISOARA',
    status: 'active',
  },
  {
    id: 5,
    firstName: 'Mihai',
    lastName: 'Stan',
    email: 'mihai.stan@example.com',
    role: 'PARTICIPANT',
    location: 'TARGU-MURES',
    status: 'active',
  },
  {
    id: 6,
    firstName: 'Ana',
    lastName: 'Radu',
    email: 'ana.radu@example.com',
    role: 'HR_USER',
    location: 'TIMISOARA',
    status: 'active',
  },
  {
    id: 7,
    firstName: 'George',
    lastName: 'Enescu',
    email: 'george.enescu@example.com',
    role: 'ADMIN',
    location: 'CLUJ-NAPOCA',
    status: 'active',
  },
  {
    id: 8,
    firstName: 'Cristina',
    lastName: 'Neagu',
    email: 'cristina.neagu@example.com',
    role: 'MARKETING_ORGANIZER',
    location: 'TARGU-MURES',
    status: 'active',
  },
];
