spring.application.name=demo

spring.profiles.active=dev

app.frontend-url=${WEB_URL:http://localhost:4200}

# Dacă CORS_ALLOWED_ORIGINS lipsește, folosește WEB_URL. 
# Dacă și WEB_URL lipsește, folosește localhost.
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:${WEB_URL:http://localhost:4200}}